<div class="vals-intro block-padding">
	<div class="block">
		<h4 id="title-section-how-it-works" >How VALS Semester of Code Works</h4>
		<div class="block-padding-no-border">
			<ol class="" id="list-how-it-works">
				<li id="how-it-works-item1" class="first">
					<strong>
					Propose a project
						<span>for approval by a mentoring open source organisation</span>
					</strong>
				</li>
				<li id="how-it-works-item2" class="second">
					<strong>Code the semester away</strong>
				</li>
				<li id="how-it-works-item3" class="third">
					<strong>
						Achieve Ultimate Glory
						<span>...and gain academic credit</span>
					</strong>
				</li>
			</ol><br/>
			<div id="block-how-it-works-description" class="description">
				<p>VALS Semester of Code is a program that offers students the chance to write code for open source projects. 
				We have worked with the open source community to identify and fund exciting 
                                projects for the upcoming academic year.</p>
			</div>
		</div>
	</div>
</div>