<div class="vals-news block-padding">
	<div class="block">
		<h4 id="title-section-how-it-works"><?php echo t('News and other information');?></h4>
			<div class="block-padding-no-border">
				<p>
					<b>New chance for participating in Semester of Code</b> <br/>
					<?php 
					echo "We decided to start a new instance of the Semester of Code offering students in the second
					semester a chance to participate as well. Projects and organisations from the first round 
					for which the participation of students
					possibility ended the 15th of December are transferred to a large extent to this round, so that there are
					still lots of projects to choose from. The program will start the <b><i>15th of January</i></b>.
					<small>(Posted: 19/12/2014)</small>";
					?>
				</p>
				<p>
					<b>Signup period starts soon now</b> <br/>
					<?php 
					echo "The <b><i>7th of January</i></b> the new instance of the Semester of Code will start, offering the option for new organisations 
					to still signup in the second round this and next week. 

					The <b><i>15th of January</i></b> the signup period for students will start.
					<small>(Posted: 06/01/2015)</small>";
					?>
				</p>

				<?php //<p>echo('<b>14/11/2014 Update.</b>&nbsp;The student registration period has been extended until 15/12/2014.
						//&nbsp;&nbsp;This is to ultimately encourage more students to participate.');</p>?>
				
				<!-- <p>
					<?php echo("We originally planned to use the well-known Melange platform used by Google's 
							Summer of Code, but at the time there was no stable version available that we could 
							use. We then deceided to start development of our own platform that follows similar 
							logic as Melange, but more tuned to our project's needs.<br /> 
							<br/>
							If you have any suggestions or other remarks, please tell us so that we can further
							improve our service.");?>
				</p> -->
				<p>
					<?php echo('Check here for external links and updates to the program, as they become available.');?>
				</p>
			</div>
	</div>
</div>
