<?php
//////// DO NOT EDIT THIS FILE /////////////////////

//////// EDIT THE FILE UNDER THE ROOT IF YOU HAVE ALREADY INSTALLED THE APPLICATION

//Copy this file to the root of the Drupal installation
//this function will be included in the index.php at top level or inside the vals_soc module
//it will lead to the constant of the url location of the SOC Drupal installation: /vals or ''
function getInitialPath($path1, $path2){
	$pos = strpos($path1, $path2);
	if (! $pos) {
		$pos = strpos($path1, '/index.php');
		if (!$pos){
			return '';
		} else {
			$arr1 = str_split($path1, $pos);
			return $arr1[0];
		}	
	}
	$arr1 = str_split($path1, $pos);
	return $arr1[0];
} 
$vals = getInitialPath($_SERVER['PHP_SELF'], '/sites/all/modules');
define('_VALS_SOC_URL', $vals);