<div class="vals-news block-padding">
	<div class="block">
		<h4 id="title-section-how-it-works"><?php echo t('News and other information');?></h4>
			<div class="block-padding-no-border">
				<p>
				<?php echo('<b>14/11/2014 Update.</b>&nbsp;The student registration period has been extended until 15/12/2014.
						&nbsp;&nbsp;This is to ultimately encourage more students to participate.');?>
				</p>
				<p>
					<?php echo("We originally planned to use the well-known Melange platform used by Google's 
							Summer of Code, but at the time there was no stable version available that we could 
							use. We then deceided to start development of our own platform that follows similar 
							logic as Melange, but more tuned to our project's needs.<br /> 
							<br/>
							If you have any suggestions or other remarks, please tell us so that we can further
							improve our service.");?>
				</p>
				<p>
					<?php echo('Check here for external links and updates to the program, as they become available.');?>
				</p>
			</div>
	</div>
</div>