<div class="vals-intro block-padding">
	<div class="block-padding-no-border">
		<h3 id="title-section-how-it-works" class="">How VALS Semester of Code Works</h3>
		<ol id="list-how-it-works">
			<li id="how-it-works-item1" class="first">
				<strong>
				Propose a project
					<span>for approval by a mentoring open source organisation</span>
				</strong>
			</li>
			<li id="how-it-works-item2" class="second">
				<strong>Code the semester away</strong>
			</li>
			<li id="how-it-works-item3" class="third">
				<strong>
					Achieve Ultimate Glory
					<span>...and gain academic credit</span>
				</strong>
			</li>
		</ol>
		<div id="block-how-it-works-description" class="description">
			<p>VALS Semester of Code is a program that offers students the chance to write code for open source projects. 
			We have worked with the open source community to identify and fund exciting projects for the upcoming summer.</p>
		</div>
	</div>
</div>