<div class="vals-news block-padding">
	<div class="block">
		<h4 id="title-section-how-it-works"><?php echo t('News and other information');?></h4>
			<div class="block-padding-no-border">
				<p>
					<?php echo("Originally we planned to use the well-known Melange software from Google's ".
							'Summer of Code, but for various good reasons we started a couple of months ago '.
							'developing this platform. Although all the basic functionality should be there, we
							expect further developments and improvements coming up the coming months.<br/><br/>'.
							'If you have remarks or suggestions, please tell us, so that we can further improve this '.
							'platform. Please have in mind that it is work in progress and that we do not develop 
							a full product; it is meant as a pilot project, so it can always be improved.');?>
				</p>
				<p>
					<?php echo('Check here for external links and updates to the program, as they become available.');?>
				</p>
			</div>
	</div>
</div>